using System.Collections.Generic;
using System;
using System.Linq;
using System.Drawing;
using System.Diagnostics;
using System.Data;
using System.Xml.Linq;
using Microsoft.VisualBasic;
using System.Collections;
using System.ComponentModel;
using System.Xml.Serialization;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



//
//This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
//
namespace Authentication.Application
	{
		namespace sms
			{
				
				///<remarks/>
				[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"), 
				System.Diagnostics.DebuggerStepThroughAttribute(), 
				System.ComponentModel.DesignerCategoryAttribute("code"), 
				System.Web.Services.WebServiceBindingAttribute(Name = "SendBinding", Namespace = "urn:Send")]public 
				partial class Send : System.Web.Services.Protocols.SoapHttpClientProtocol
					{
						
						private System.Threading.SendOrPostCallback SendMultiSMSOperationCompleted;
						
						private System.Threading.SendOrPostCallback SendSMSOperationCompleted;
						
						private System.Threading.SendOrPostCallback GetCreditOperationCompleted;
						
						private System.Threading.SendOrPostCallback GetStatusOperationCompleted;
						
						private bool useDefaultCredentialsSetExplicitly;
						
						///<remarks/>
						public Send()
							{
								this.Url = global::$safeprojectname$.My.Settings.Default.WindowsApplication1_sms_Send;
								if (this.IsLocalFileSystemWebService(this.Url) == true)
									{
										this.UseDefaultCredentials = true;
										this.useDefaultCredentialsSetExplicitly = false;
									}
								else
									{
										this.useDefaultCredentialsSetExplicitly = true;
									}
							}
						
public new string Url
							{
								get
									{
										return base.Url;
									}
								set
									{
										if (((this.IsLocalFileSystemWebService(base.Url) == true) 
											&& (this.useDefaultCredentialsSetExplicitly == false)) 
											&& (this.IsLocalFileSystemWebService(value) == false))
											{
												base.UseDefaultCredentials = false;
											}
										base.Url = value;
									}
							}
						
public new bool UseDefaultCredentials
							{
								get
									{
										return base.UseDefaultCredentials;
									}
								set
									{
										base.UseDefaultCredentials = value;
										this.useDefaultCredentialsSetExplicitly = true;
									}
							}
						
						///<remarks/>
						private SendMultiSMSCompletedEventHandler SendMultiSMSCompletedEvent;
						public event SendMultiSMSCompletedEventHandler SendMultiSMSCompleted
							{
								add
									{
										SendMultiSMSCompletedEvent = (SendMultiSMSCompletedEventHandler) System.Delegate.Combine(SendMultiSMSCompletedEvent, value);
									}
								remove
									{
										SendMultiSMSCompletedEvent = (SendMultiSMSCompletedEventHandler) System.Delegate.Remove(SendMultiSMSCompletedEvent, value);
									}
							}
						
						
						///<remarks/>
						private SendSMSCompletedEventHandler SendSMSCompletedEvent;
						public event SendSMSCompletedEventHandler SendSMSCompleted
							{
								add
									{
										SendSMSCompletedEvent = (SendSMSCompletedEventHandler) System.Delegate.Combine(SendSMSCompletedEvent, value);
									}
								remove
									{
										SendSMSCompletedEvent = (SendSMSCompletedEventHandler) System.Delegate.Remove(SendSMSCompletedEvent, value);
									}
							}
						
						
						///<remarks/>
						private GetCreditCompletedEventHandler GetCreditCompletedEvent;
						public event GetCreditCompletedEventHandler GetCreditCompleted
							{
								add
									{
										GetCreditCompletedEvent = (GetCreditCompletedEventHandler) System.Delegate.Combine(GetCreditCompletedEvent, value);
									}
								remove
									{
										GetCreditCompletedEvent = (GetCreditCompletedEventHandler) System.Delegate.Remove(GetCreditCompletedEvent, value);
									}
							}
						
						
						///<remarks/>
						private GetStatusCompletedEventHandler GetStatusCompletedEvent;
						public event GetStatusCompletedEventHandler GetStatusCompleted
							{
								add
									{
										GetStatusCompletedEvent = (GetStatusCompletedEventHandler) System.Delegate.Combine(GetStatusCompletedEvent, value);
									}
								remove
									{
										GetStatusCompletedEvent = (GetStatusCompletedEventHandler) System.Delegate.Remove(GetStatusCompletedEvent, value);
									}
							}
						
						
						///<remarks/>
						[System.Web.Services.Protocols.SoapRpcMethodAttribute("SendMultiSMS", RequestNamespace = "Send_API", ResponseNamespace = "Send_API")][return: System.Xml.Serialization.SoapElementAttribute("return")]
						public string[] SendMultiSMS(string[] fromNum, string[] toNum, string[] Content, string[] Type, string Username, string Password)
							{
								object[] results = this.Invoke("SendMultiSMS", new object[] {fromNum, toNum, Content, Type, Username, Password});
								return ((string[]) (results[0]));
							}
						
						///<remarks/>
						public void SendMultiSMSAsync(string[] fromNum, string[] toNum, string[] Content, string[] Type, string Username, string Password)
							{
								this.SendMultiSMSAsync(fromNum, toNum, Content, Type, Username, Password, null);
							}
						
						///<remarks/>
						public void SendMultiSMSAsync(string[] fromNum, string[] toNum, string[] Content, string[] Type, string Username, string Password, object userState)
							{
								if (this.SendMultiSMSOperationCompleted == null)
									{
										this.SendMultiSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMultiSMSOperationCompleted);
									}
								this.InvokeAsync("SendMultiSMS", new object[] {fromNum, toNum, Content, Type, Username, Password}, this.SendMultiSMSOperationCompleted, userState);
							}
						
						private void OnSendMultiSMSOperationCompleted(object arg)
							{
								if (!((this.SendMultiSMSCompletedEvent) == null))
									{
										System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = (System.Web.Services.Protocols.InvokeCompletedEventArgs) arg;
										if (SendMultiSMSCompletedEvent != null)
											SendMultiSMSCompletedEvent(this, new SendMultiSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
									}
							}
						
						///<remarks/>
						[System.Web.Services.Protocols.SoapRpcMethodAttribute("SendSMS", RequestNamespace = "Send_API", ResponseNamespace = "Send_API")][return: System.Xml.Serialization.SoapElementAttribute("return")]
						public string[] SendSMS(string fromNum, string[] toNum, string Content, string Type, string Username, string Password)
							{
								object[] results = this.Invoke("SendSMS", new object[] {fromNum, toNum, Content, Type, Username, Password});
								return ((string[]) (results[0]));
							}
						
						///<remarks/>
						public void SendSMSAsync(string fromNum, string[] toNum, string Content, string Type, string Username, string Password)
							{
								this.SendSMSAsync(fromNum, toNum, Content, Type, Username, Password, null);
							}
						
						///<remarks/>
						public void SendSMSAsync(string fromNum, string[] toNum, string Content, string Type, string Username, string Password, object userState)
							{
								if (this.SendSMSOperationCompleted == null)
									{
										this.SendSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMSOperationCompleted);
									}
								this.InvokeAsync("SendSMS", new object[] {fromNum, toNum, Content, Type, Username, Password}, this.SendSMSOperationCompleted, userState);
							}
						
						private void OnSendSMSOperationCompleted(object arg)
							{
								if (!((this.SendSMSCompletedEvent) == null))
									{
										System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = (System.Web.Services.Protocols.InvokeCompletedEventArgs) arg;
										if (SendSMSCompletedEvent != null)
											SendSMSCompletedEvent(this, new SendSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
									}
							}
						
						///<remarks/>
						[System.Web.Services.Protocols.SoapRpcMethodAttribute("GetCredit", RequestNamespace = "Send_API", ResponseNamespace = "Send_API")][return: System.Xml.Serialization.SoapElementAttribute("return")]
						public string GetCredit(string Username, string Password)
							{
								object[] results = this.Invoke("GetCredit", new object[] {Username, Password});
								return System.Convert.ToString(results[0]);
							}
						
						///<remarks/>
						public void GetCreditAsync(string Username, string Password)
							{
								this.GetCreditAsync(Username, Password, null);
							}
						
						///<remarks/>
						public void GetCreditAsync(string Username, string Password, object userState)
							{
								if (this.GetCreditOperationCompleted == null)
									{
										this.GetCreditOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCreditOperationCompleted);
									}
								this.InvokeAsync("GetCredit", new object[] {Username, Password}, this.GetCreditOperationCompleted, userState);
							}
						
						private void OnGetCreditOperationCompleted(object arg)
							{
								if (!((this.GetCreditCompletedEvent) == null))
									{
										System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = (System.Web.Services.Protocols.InvokeCompletedEventArgs) arg;
										if (GetCreditCompletedEvent != null)
											GetCreditCompletedEvent(this, new GetCreditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
									}
							}
						
						///<remarks/>
						[System.Web.Services.Protocols.SoapRpcMethodAttribute("GetStatus", RequestNamespace = "Send_API", ResponseNamespace = "Send_API")][return: System.Xml.Serialization.SoapElementAttribute("return")]
						public string[] GetStatus(string Username, string Password, string[] Unique_ids)
							{
								object[] results = this.Invoke("GetStatus", new object[] {Username, Password, Unique_ids});
								return ((string[]) (results[0]));
							}
						
						///<remarks/>
						public void GetStatusAsync(string Username, string Password, string[] Unique_ids)
							{
								this.GetStatusAsync(Username, Password, Unique_ids, null);
							}
						
						///<remarks/>
						public void GetStatusAsync(string Username, string Password, string[] Unique_ids, object userState)
							{
								if (this.GetStatusOperationCompleted == null)
									{
										this.GetStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStatusOperationCompleted);
									}
								this.InvokeAsync("GetStatus", new object[] {Username, Password, Unique_ids}, this.GetStatusOperationCompleted, userState);
							}
						
						private void OnGetStatusOperationCompleted(object arg)
							{
								if (!((this.GetStatusCompletedEvent) == null))
									{
										System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = (System.Web.Services.Protocols.InvokeCompletedEventArgs) arg;
										if (GetStatusCompletedEvent != null)
											GetStatusCompletedEvent(this, new GetStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
									}
							}
						
						///<remarks/>
						public new void CancelAsync(object userState)
							{
								base.CancelAsync(userState);
							}
						
						private bool IsLocalFileSystemWebService(string url)
							{
								if ((url == null) 
									|| (url == string.Empty))
									{
										return false;
									}
								System.Uri wsUri = new System.Uri(url);
								if ((wsUri.Port >= 1024) 
									&& (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))
									{
										return true;
									}
								return false;
							}
					}
				
				///<remarks/>
				[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]public delegate void SendMultiSMSCompletedEventHandler(object sender, SendMultiSMSCompletedEventArgs e);
				
				///<remarks/>
				[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"), 
				System.Diagnostics.DebuggerStepThroughAttribute(), 
				System.ComponentModel.DesignerCategoryAttribute("code")]public 
				partial class SendMultiSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
					{
						
						private object[] results;
						
						internal SendMultiSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : base(exception, cancelled, userState)
							{
								this.results = results;
							}
						
						///<remarks/>
public string[] Result
							{
								get
									{
										this.RaiseExceptionIfNecessary();
										return ((string[]) (this.results[0]));
									}
							}
					}
				
				///<remarks/>
				[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]public delegate void SendSMSCompletedEventHandler(object sender, SendSMSCompletedEventArgs e);
				
				///<remarks/>
				[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"), 
				System.Diagnostics.DebuggerStepThroughAttribute(), 
				System.ComponentModel.DesignerCategoryAttribute("code")]public 
				partial class SendSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
					{
						
						private object[] results;
						
						internal SendSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : base(exception, cancelled, userState)
							{
								this.results = results;
							}
						
						///<remarks/>
public string[] Result
							{
								get
									{
										this.RaiseExceptionIfNecessary();
										return ((string[]) (this.results[0]));
									}
							}
					}
				
				///<remarks/>
				[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]public delegate void GetCreditCompletedEventHandler(object sender, GetCreditCompletedEventArgs e);
				
				///<remarks/>
				[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"), 
				System.Diagnostics.DebuggerStepThroughAttribute(), 
				System.ComponentModel.DesignerCategoryAttribute("code")]public 
				partial class GetCreditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
					{
						
						private object[] results;
						
						internal GetCreditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : base(exception, cancelled, userState)
							{
								this.results = results;
							}
						
						///<remarks/>
public string Result
							{
								get
									{
										this.RaiseExceptionIfNecessary();
										return System.Convert.ToString(this.results[0]);
									}
							}
					}
				
				///<remarks/>
				[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]public delegate void GetStatusCompletedEventHandler(object sender, GetStatusCompletedEventArgs e);
				
				///<remarks/>
				[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"), 
				System.Diagnostics.DebuggerStepThroughAttribute(), 
				System.ComponentModel.DesignerCategoryAttribute("code")]public 
				partial class GetStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
					{
						
						private object[] results;
						
						internal GetStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : base(exception, cancelled, userState)
							{
								this.results = results;
							}
						
						///<remarks/>
public string[] Result
							{
								get
									{
										this.RaiseExceptionIfNecessary();
										return ((string[]) (this.results[0]));
									}
							}
					}
			}
		
	}

